<a href="https://colab.research.google.com/github/egorik3z/ML/blob/master/ML01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Подключение модуля
import numpy as np

In [ ]:
#Создание массива
arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1[0])
print(arr1[2])
print(arr1[-1])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3
3


In [ ]:
#Создание двумерного массива
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print(type(arr_2d))
print(arr_2d.shape)
print(arr_2d[0, 0])
print(arr_2d[1, 2])
print(arr_2d[1, 0])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
1
6
4


In [ ]:
#Фиксированный массив
arr_fix=np.ndarray([2,3])
print(arr_fix)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [ ]:
#Массив нулей
zeros=np.zeros([2,2])
print(zeros)

[[0. 0.]
 [0. 0.]]


In [ ]:
#Массив констант
arr_const=np.full((2,3),5)
print(arr_const)

[[5 5 5]
 [5 5 5]]


In [ ]:
#Массив единиц
arr_ones=np.ones((2,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#массив с единичной ГД
arr_eye=np.eye(4,4)
print(arr_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#массив нулей с аналогичной размерностью
arr_zerlike=np.zeros_like(arr_eye)
print(arr_zerlike)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Рандомный массив
arr_random=np.random.random((3,3))
print(arr_random)

[[0.40284586 0.56994345 0.70927832]
 [0.4777219  0.30374985 0.84196082]
 [0.39225461 0.18128387 0.45507694]]


In [ ]:
# Аналог функции range
np.arange(start=1, stop=10, step=1.5)
np.linspace(start=1, stop=5, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
arr=list(range(1,11))

print(arr[8:2:-2])
print(arr[:5])
print(arr[:-1])
new_arr = list(range(1, 11))
new_arr[1:5] = arr[:4]
print(new_arr)
print(arr[:5:-2])

[9, 7, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 1, 2, 3, 4, 6, 7, 8, 9, 10]
[10, 8]


In [ ]:
#Перевернуть список
data = list(range(10))
print(data)
print(data[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [ ]:
#Массив без первого и 2х последних элементов
data = list(range(10))
print(data[1:8:1])

[1, 2, 3, 4, 5, 6, 7]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[2])
print(arr[2, :])

[ 9 10 11 12]
[ 9 10 11 12]


In [ ]:
print(arr[:, 1])


[ 2  6 10]


In [ ]:
print(arr[1, :2])


[5 6]


In [ ]:
new_arr = arr.copy()
print(new_arr)

new_arr[2, :] = arr[1, :]
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
arr = np.array([[1.5, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.dtype)


float64


In [ ]:
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(arr)
print(arr.dtype)


[[ 1  1  2]
 [-1  2 -1]]
int64


In [ ]:
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]])
print(arr)
print(arr.dtype)
print('----------')
arr = arr.astype(int)
print(arr)
print(arr.dtype)

[[ 1.1  1.6  2.4]
 [-1.7  2.6 -1.2]]
float64
----------
[[ 1  1  2]
 [-1  2 -1]]
int64


In [ ]:
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(arr)

arr[0, 1] = 10.12
print(arr)

[[ 1  1  2]
 [-1  2 -1]]
[[ 1 10  2]
 [-1  2 -1]]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
result = arr > 6
print(result)
print(result.dtype)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
bool


In [ ]:
result_1 = arr > 6
result_2 = arr < 10
print(result_1)
print(result_2)

print('----------')

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]]
----------


In [ ]:
print(result_1 & result_2)
print((arr > 6) & (arr < 10))

[[False False False False]
 [False False  True  True]
 [ True False False False]]
[[False False False False]
 [False False  True  True]
 [ True False False False]]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)
result=np.any((arr>5)&(arr<8))
print(result)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
True


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
mask = arr > 6
print(mask)
print(arr[mask])

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 7  8  9 10 11 12]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.flatten())

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [ ]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
k = 1.5

print(k*x)

[[1.5 3. ]
 [4.5 6. ]]


In [ ]:
v = np.array([1, 2])

In [ ]:
print(x @ v)
print(x.dot(v))
print(np.dot(x, v))

[ 5. 11.]
[ 5. 11.]
[ 5. 11.]


In [ ]:
w = np.array([3, 4])

print(w @ v)
print(w.dot(v))
print(np.dot(w, v))

11
11
11


In [ ]:
print(x @ y)
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
print('--------')
print(np.transpose(x))
print(x.T)
print(x.T.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
--------
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
x = np.array([[1, 2, 3], [5, 4, 3]])
print(x)

[[1 2 3]
 [5 4 3]]


In [ ]:
print(np.mean(x))
print(np.mean(x, axis=None))

3.0
3.0


In [ ]:
print(np.sum(x))
print(np.sum(x, axis=None))

18
18


In [ ]:
print(np.mean(x, axis=0))

[3. 3. 3.]


In [ ]:
print(np.mean(x, axis=1))

[2. 4.]


In [ ]:
data = np.random.randint(low=0, high=5, size=(3, 6))
print(data)
print(np.sum(data, axis=0))

[[1 1 3 0 4 0]
 [0 3 2 2 2 0]
 [1 2 0 0 3 4]]
[2 6 5 2 9 4]


In [ ]:
vec = np.arange(4)
mtrx = np.ones((3, 4))
print(vec)
print(mtrx)

[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
result = np.empty_like(mtrx)

for i_row in range(mtrx.shape[0]):
    result[i_row,:] = mtrx[i_row,:] * vec

print(result)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [ ]:
vec_m = np.tile(vec, reps=(3, 1))
print(vec_m)
print(vec_m * mtrx)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [ ]:
print(vec * mtrx)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [ ]:
print(2 * mtrx)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [ ]:

x = np.ones((4, 1, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print((x*y).shape)

(4, 3, 2)


In [ ]:
x = np.ones((3, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print((x*y).shape)

(4, 3, 2)


In [ ]:
x = np.ones((1, 3, 2))
y = np.random.randint(0, 5, size=(5, 1, 2))

print((x*y).shape)

(5, 3, 2)


In [ ]:
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
mtrx = np.ndarray((4, 5), dtype=np.int32)
mtrx[0, :] = arr[:5]
mtrx[1, :] = arr[5:10]
mtrx[2, :] = arr[10:15]
mtrx[3, :] = arr[15:]

print(mtrx)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
print(arr.reshape((4, 5)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
print(arr.reshape((2, 10)))
print(arr.reshape((5, 4)))
print(arr.reshape((20, 1)))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [ ]:
print(arr.reshape((4, -1)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
x = np.arange(10).reshape((2, 5))
y = np.arange(15).reshape((3, 5))

print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
print(np.concatenate((x, y), axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
x = np.arange(9).reshape((3, 3))
y = np.arange(12).reshape((3, 4))
z = np.arange(15).reshape((3, 5))

print(x)
print(y)
print(z)
print(np.concatenate((x,y,z),axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  0  1  2  3  0  1  2  3  4]
 [ 3  4  5  4  5  6  7  5  6  7  8  9]
 [ 6  7  8  8  9 10 11 10 11 12 13 14]]


In [ ]:
x = np.arange(1, 10).reshape((3, 3))
print(x)
y=np.ones((3,1),dtype=int)
print(y)
print(np.concatenate((y,x),axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [1]
 [1]]
[[1 1 2 3]
 [1 4 5 6]
 [1 7 8 9]]


In [ ]:
unsorted_arr = np.array([2, 4, 5, 1, 2, 7, 5, 0, -1, 3, 5])
sorted_arr = np.sort(unsorted_arr)

print(unsorted_arr)
print(sorted_arr)

[ 2  4  5  1  2  7  5  0 -1  3  5]
[-1  0  1  2  2  3  4  5  5  5  7]


In [ ]:

sorted_indices = np.argsort(unsorted_arr)
print(sorted_indices)

[ 8  7  3  0  4  9  1  2  6 10  5]


In [ ]:
print(unsorted_arr[sorted_indices])

[-1  0  1  2  2  3  4  5  5  5  7]


In [ ]:
arr = np.array([
    [11, -1, 1, 3, 5],
    [6, 1, 0, -1, 10],
    [1, 3, 2, 3, 6],
    [5, 2, 7, 8, 9],
])

print(arr)
max_arg=np.argmax(arr,axis=0)
min_arg=np.argmin(arr,axis=0)
print(max_arg)
print(min_arg)

[[11 -1  1  3  5]
 [ 6  1  0 -1 10]
 [ 1  3  2  3  6]
 [ 5  2  7  8  9]]
[0 2 3 3 1]
[2 0 1 1 0]


In [ ]:
arr = np.array([
    [11, 2, 1, 3, 5],
    [6, 2, 0, -1, 10],
    [1, 3, 2, 3, 5],
    [5, 2, 7, 8, 9],
])
print(arr)
new_arr=np.sort(arr,axis=0)
print(new_arr)

[[11  2  1  3  5]
 [ 6  2  0 -1 10]
 [ 1  3  2  3  5]
 [ 5  2  7  8  9]]
[[ 1  2  0 -1  5]
 [ 5  2  1  3  5]
 [ 6  2  2  3  9]
 [11  3  7  8 10]]


In [ ]:
#ЗАДАЧКИ
#Создайте массив, состоящий из случайных элементов в диапазоне $[-10; 20]$ размером $(5, 7)$:
arr = np.random.randint(low=-10, high=20, size=(5, 7))
print(arr)

[[  8   9  -2   2  -8  -9  -4]
 [  3  -7  -3   8  -9  -8   9]
 [-10   5   1  19   5  -4  -2]
 [  1  15  12  17  -4  12   8]
 [ -9   0  10  -8   6   9  -3]]


In [ ]:
#Добавьте границу в виде нулей со всех сторон 2D массива:
data = np.arange(1, 16).reshape((3, 5))
print(data)
zer_arr=np.zeros((data.shape[0],1),dtype=int)
new_arr=np.concatenate((zer_arr,data,zer_arr), axis=1)
zer_arr2=np.zeros((1,new_arr.shape[1]),dtype=int)
new_arr=np.concatenate((zer_arr2,new_arr,zer_arr2),axis=0)
print()
print(new_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0]]


In [ ]:
#Разберитесь с функцией np.clip() и произведите ограничение массива, чтобы в нем значения были не более шести и не менее двух:
data = np.arange(1, 16).reshape((3, 5))
print(data)
data1=np.clip(data,2,6)
print()
print(data1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[[2 2 3 4 5]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [ ]:
#Произведите модификацию массива так, чтобы значение в колонке результата соответствовало исходному значению, возведенному в степень индекса колонки:
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)
print('------------')
data1=np.arange(data.shape[1])
data2=data**data1
print(data2)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
------------
[[ 1  2  4  8 16]
 [ 1  2  4  8 16]
 [ 1  2  4  8 16]]


In [ ]:
#Умножьте каждую колонку на ее индекс:
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)
data1=np.arange(data.shape[1])
data2=data*data1
print(data2)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[0 2 4 6 8]
 [0 2 4 6 8]
 [0 2 4 6 8]]


In [ ]:
#Умножьте каждый четный ряд в матрице на вектор
data = np.repeat(np.arange(1, 8), 4).reshape(7, 4)
vec = np.array([1, 2, 1, 2])
print(data)
print()
for i in range(data.shape[0]):
    if i%2==0:
      data[i,:]=data[i,:]*vec
print (data)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]

[[ 1  2  1  2]
 [ 2  2  2  2]
 [ 3  6  3  6]
 [ 4  4  4  4]
 [ 5 10  5 10]
 [ 6  6  6  6]
 [ 7 14  7 14]]


In [ ]:
#Определите индексы двух наибольших элементов в матрице по каждому ряду:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print()
data_argsort=np.argsort(data, axis=1)
new_data=data_argsort[:,(-1,-2)]
print(new_data)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]

[[4 1]
 [1 2]
 [3 1]
 [5 3]]


In [34]:
#Выберите две случайные колонки из массива:
import random
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print()
data1=data[:,(random.randint(0, data.shape[0]),random.randint(0, data.shape[0]))]
print(data1)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]

[[20  2]
 [ 7 23]
 [ 8  9]
 [ 4 24]]


In [85]:
#Создайте массив размером $(10, 3)$, который состоит из повторяющихся рядов исходного массива:
data = np.arange(9).reshape(3, 3)
print(data)
print()
data1=np.tile(data,(3,1))
data1=np.random.permutation(data1)
print(data1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[6 7 8]
 [0 1 2]
 [3 4 5]
 [0 1 2]
 [6 7 8]
 [3 4 5]
 [6 7 8]
 [3 4 5]
 [0 1 2]]


In [65]:
#Соберите массив, состоящий из элементов 2й и 4й колонок и строк с 1й по 3ю:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print()
data1=data[:,(2,4)]
data1=data1[(1,2,3),:]
print(data1)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]

[[23 22]
 [ 9  0]
 [33  7]]


In [84]:
#Инвертируйте порядок элементов в последних двух колонках:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print()
data1=data[:,(0,1,2,3)]
data2=data[:,(4,5)]
data2=np.flip(data2, axis=0)
data1=np.concatenate((data1,data2),axis=1)
print(data1)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]

[[20 22  2 14  3 40]
 [ 7 25 23  3  7  6]
 [ 8 16  9 22  0  9]
 [14  9 33 21 22 15]
 [ 4 24 24 28 25  8]]


In [74]:
data=np.array([[1,2],[3,4],[5,6]])
print(data)
print()
data1=np.flip(data,axis=0)
print(data1)

[[1 2]
 [3 4]
 [5 6]]

[[5 6]
 [3 4]
 [1 2]]
