<a href="https://colab.research.google.com/github/egorik3z/ML/blob/master/ML03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install pandas==1.1.2

     |████████████████████████████████| 10.5MB 2.8MB/s 
  Found existing installation: pandas 1.1.0
    Uninstalling pandas-1.1.0:
      Successfully uninstalled pandas-1.1.0


In [1]:
import pandas as pd


In [2]:
import numpy as np

In [3]:
arr = np.random.randint(0, 10, size=(5, 3))
print(arr)

[[8 0 8]
 [8 0 4]
 [1 0 4]
 [3 2 3]
 [9 1 6]]


In [4]:
# Создание фрейма - просто вызвать конструктор
df = pd.DataFrame(data=arr)
df

0  1  2
0  8  0  8
1  8  0  4
2  1  0  4
3  3  2  3
4  9  1  6

In [20]:
arr = np.random.randint(0, 10, size=(5, 3))
arr
arr1=pd.DataFrame(data=arr,index=['a','b','c','d','f'],columns=['col_1','col_2','col_3'])
arr1

col_1  col_2  col_3
a      0      2      9
b      0      7      3
c      0      0      7
d      4      5      8
f      1      6      8

In [21]:
data = {
    'test_1_mark': [4.6, 3.8, 5.0, 4.5],
    'test_2_mark': [5.0, 3.9, 4.7, 4.5]
}

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          4.7
3          4.5          4.5

In [22]:
data = [
    {
        'test_1_mark': 4.6,
        'test_2_mark': 5.0
    },
    {
        'test_1_mark': 3.8,
        'test_2_mark': 3.9
    },
    {
        'test_1_mark': 5.0
    },
]

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          NaN

In [24]:

df = pd.DataFrame({'A': 1.,
                   'B': pd.Timestamp('20130102'),
                   'C': np.array([2.] * 4, dtype='float32'),
                   'D': np.array([3] * 4, dtype='int32'),
                   'E': pd.Categorical(["test", "train", "test", "train"]),
                   'F': 'foo'})
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   A       4 non-null      float64       
 1   B       4 non-null      datetime64[ns]
 2   C       4 non-null      float32       
 3   D       4 non-null      int32         
 4   E       4 non-null      category      
 5   F       4 non-null      object        
dtypes: category(1), datetime64[ns](1), float32(1), float64(1), int32(1), object(1)
memory usage: 356.0+ bytes


In [29]:
df = pd.DataFrame(
    data=np.random.randint(-10, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(4)

x1  x2  x3
0  -5 -10   7
1  -2   4  -9
2  -8  -8  -1
3   7   1   7

In [30]:
df.tail(4)

x1  x2  x3
11 -10   7   5
12  -7  -6 -10
13  -4   9 -10
14   0   0   7

In [31]:
df.describe()


x1         x2         x3
count  15.000000  15.000000  15.000000
mean   -2.333333  -1.533333  -0.133333
std     5.550633   6.937133   6.738659
min   -10.000000 -10.000000 -10.000000
25%    -6.500000  -8.000000  -6.500000
50%    -3.000000   0.000000   2.000000
75%     1.500000   4.000000   6.500000
max     7.000000   9.000000   7.000000

In [32]:
df.index


RangeIndex(start=0, stop=15, step=1)

In [33]:
list(df.index)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [34]:
df.columns


Index(['x1', 'x2', 'x3'], dtype='object')

In [35]:
df.shape


(15, 3)

In [36]:
df.to_numpy()


array([[ -5, -10,   7],
       [ -2,   4,  -9],
       [ -8,  -8,  -1],
       [  7,   1,   7],
       [  4,  -6,   6],
       [  3,   4,   7],
       [ -6, -10,  -7],
       [ -3,   8,  -6],
       [  6,  -8,  -2],
       [-10,  -9,   2],
       [  0,   1,   2],
       [-10,   7,   5],
       [ -7,  -6, -10],
       [ -4,   9, -10],
       [  0,   0,   7]])

In [37]:
df.T


0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
x1  -5  -2  -8   7   4   3  -6  -3   6 -10   0 -10  -7  -4   0
x2 -10   4  -8   1  -6   4 -10   8  -8  -9   1   7  -6   9   0
x3   7  -9  -1   7   6   7  -7  -6  -2   2   2   5 -10 -10   7

In [38]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)

df

x1  x2  x3
0   6   5   0
1   8   4   9
2   5   6   2
3   2   8   5
4   4   9   0

In [39]:
print(df['x1'])
print(type(df['x1']))

0    6
1    8
2    5
3    2
4    4
Name: x1, dtype: int64
<class 'pandas.core.series.Series'>


In [42]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [43]:
df.iloc[2]


feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [44]:
df.loc['C']


feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [45]:
df.iloc[2, 1]


1.4285714285714286

In [46]:
df.loc['C', 'feature2']


1.4285714285714286

In [47]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [100]:
df.iloc[2:9,0:3:2]

x1  x3
2   2   2
3   5   3
4   0   0
5   1   1
6   8   3
7   3   5
8   8   7

In [65]:
df.loc['C':'I','feature1''feature3']

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

In [66]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   9   6   2
1   7   3   4
2   6   0   1

In [67]:
df['x1'] > 5


0      True
1      True
2      True
3     False
4      True
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12     True
13     True
14    False
Name: x1, dtype: bool

In [68]:
mask = df['x1'] > 5
df[mask]

x1  x2  x3
0    9   6   2
1    7   3   4
2    6   0   1
4    9   3   8
6    7   8   8
12   7   6   9
13   9   1   6

In [69]:
df[~(df['x1'] > 5)]

x1  x2  x3
3    2   2   6
5    5   5   0
7    5   6   8
8    3   4   5
9    5   3   9
10   0   5   7
11   4   4   0
14   1   7   8

In [70]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   6   9   5
1   5   5   1
2   2   5   2

In [81]:
mask = (df['x1'] > 3)&(df['x3']<8)
df[mask].loc[:,('x1','x2')]

x1  x2
0    6   9
1    5   5
3    5   3
6    8   8
8    8   8
9    4   3
10   9   4
12   9   8
13   7   1

In [101]:

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   0   0   7
1   3   8   0
2   7   9   4

In [102]:
df['x1+x2'] = df['x1'] + df['x2']
df.head(3)

x1  x2  x3  x1+x2
0   0   0   7      0
1   3   8   0     11
2   7   9   4     16

In [103]:
df['x1*x3'] = df['x1'] * df['x3']
df.head(3)

x1  x2  x3  x1+x2  x1*x3
0   0   0   7      0      0
1   3   8   0     11      0
2   7   9   4     16     28

In [104]:
df['x1'].mean()

4.466666666666667

In [105]:
df['x2_exp'] = np.exp(df['x2'])
df.head(3)

x1  x2  x3  x1+x2  x1*x3       x2_exp
0   0   0   7      0      0     1.000000
1   3   8   0     11      0  2980.957987
2   7   9   4     16     28  8103.083928

In [106]:

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(3, 3)), 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
0   9   5   7
1   4   9   1
2   6   3   5

In [107]:
def my_func(x):
    print(type(x))
    print(x)
    return x*2

df['result'] = df['x1'].apply(my_func)
df

<class 'int'>
9
<class 'int'>
4
<class 'int'>
6


x1  x2  x3  result
0   9   5   7      18
1   4   9   1       8
2   6   3   5      12

In [116]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   5   0   3
1   8   5   4
2   9   8   5

In [118]:
df_renamed=df.rename(
    columns={
        'x1': 'new_name_for_x1',
        'x3': 'that_not_x3' 
    },
    #inplace=True
)
df_renamed.head(3)

new_name_for_x1  x2  that_not_x3
0                5   0            3
1                8   5            4
2                9   8            5

In [124]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    index=['A', 'B', 'C', 'D', 'E'], 
    columns=['x1', 'x2', 'x3']
)
df.rename(columns={
    'x1':'new1',
    'x3':'new3'
},
index={
    'A':'a1',
    'C':'c1'
},
inplace=True)
df

new1  x2  new3
a1     0   7     1
B      2   9     9
c1     2   4     0
D      6   8     4
E      0   5     1

In [125]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   0   6   3
1   2   0   5
2   4   3   4

In [126]:
df.drop(columns=['x2'], inplace=True)
df.head(3)

x1  x3
0   0   3
1   2   5
2   4   4

In [127]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.iloc[0, :2] = np.nan
df.iloc[2, 1:] = np.nan

df

x1   x2   x3
0  NaN  NaN  3.0
1  1.0  9.0  9.0
2  1.0  NaN  NaN
3  0.0  2.0  1.0
4  0.0  1.0  4.0

In [128]:
df.isna()

x1     x2     x3
0   True   True  False
1  False  False  False
2  False   True   True
3  False  False  False
4  False  False  False

In [129]:
df.isna().sum()

x1    1
x2    2
x3    1
dtype: int64

In [130]:
df['x2'].fillna(3, inplace=True)
df

x1   x2   x3
0  NaN  3.0  3.0
1  1.0  9.0  9.0
2  1.0  3.0  NaN
3  0.0  2.0  1.0
4  0.0  1.0  4.0

In [131]:
df = pd.DataFrame({
    'col1': ['high', 'high', 'low', 'med', 'low', 'low', 'med', 'low', 'low', 'high'],
    'col2': [0, 1, 1, 2, 3, 1, 1, 2, 2, 2]
})
df

col1  col2
0  high     0
1  high     1
2   low     1
3   med     2
4   low     3
5   low     1
6   med     1
7   low     2
8   low     2
9  high     2

In [132]:
df.nunique()


col1    3
col2    4
dtype: int64

In [133]:
df['col1'].value_counts()


low     5
high    3
med     2
Name: col1, dtype: int64

In [134]:
df['col2'].value_counts()


2    4
1    4
3    1
0    1
Name: col2, dtype: int64

In [135]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['col_one', 'col_two', 'col_three'])
df

col_one  col_two  col_three
mouse         1        2          3
rabbit        4        5          6

In [136]:
df.filter(regex='o$', axis='columns')


col_two
mouse         2
rabbit        5

In [140]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9])),
                  index=['dog in house', 'cat in house', 'pig in farm'],
                  columns=['x1', 'x2', 'x3'])
df
df.filter(like='house',axis='index')


x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6

In [141]:
df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
}, index=['A', 'B', 'C', 'D', 'E', 'F'])
df

col1  col2  col3 col4
A    A     2     0    a
B    A     1     1    B
C    B     9     9    c
D  NaN     8     4    D
E    D     7     2    e
F    C     4     3    F

In [142]:
df.sort_values(by='col2', axis='rows')


col1  col2  col3 col4
B    A     1     1    B
A    A     2     0    a
F    C     4     3    F
E    D     7     2    e
D  NaN     8     4    D
C    B     9     9    c

In [154]:
df = pd.DataFrame(
    np.random.randint(0, 20, size=(5, 5)), 
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)
df.sort_values(by=3,axis=1,ascending=False)

col1  col3  col2  col4  col5
0     6     8     6     1    15
1    10     0    13     5    16
2    15     0    19     0     7
3    17    14     6     1     1
4    11    18     7     5    11

In [155]:
df = pd.DataFrame({
    'temp': [59, 22, -10, 38, 20, 40, 38, 47, 20, 15, 13, 44, 57, 32, 38]
})
df.head()

temp
0    59
1    22
2   -10
3    38
4    20

In [156]:
df['temp_cat'] = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    labels=['low', 'medium', 'high'],
    # Флаг, чтобы самое левое значение границы входило в первый диапазон
    include_lowest=True
)
df.head()

temp temp_cat
0    59     high
1    22   medium
2   -10      low
3    38     high
4    20   medium

In [157]:
df['temp_cat'].dtype

CategoricalDtype(categories=['low', 'medium', 'high'], ordered=True)

In [158]:
result_after_cut = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    include_lowest=True
)

In [159]:
result_after_cut.unique()


[(25.0, 60.0], (10.0, 25.0], (-10.001, 10.0]]
Categories (3, interval[float64]): [(-10.001, 10.0] < (10.0, 25.0] < (25.0, 60.0]]

In [161]:
result_after_cut = pd.cut(
    x=df['temp'],
    bins=4
)
result_after_cut.unique()

[(41.75, 59.0], (7.25, 24.5], (-10.069, 7.25], (24.5, 41.75]]
Categories (4, interval[float64]): [(-10.069, 7.25] < (7.25, 24.5] < (24.5, 41.75] < (41.75, 59.0]]

In [166]:
df = pd.DataFrame({
    'quality': [ 7, 67, 21, 38,  2, -2, 79, 22,  5, 31, 77, 72, 23, 64, 99]
})
df.head()
df['q_cat'] = pd.cut(
    x=df['quality'],
    bins=[0, 20, 45, 85, 100],
    labels=['bad', 'mid', 'good','excellent'],
    include_lowest=True
)
df

quality      q_cat
0         7        bad
1        67       good
2        21        mid
3        38        mid
4         2        bad
5        -2        NaN
6        79       good
7        22        mid
8         5        bad
9        31        mid
10       77       good
11       72       good
12       23        mid
13       64       good
14       99  excellent

In [167]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [168]:
df.aggregate(['min', 'mean'], axis='rows')


A    B    C
min   1.0  2.0  3.0
mean  4.0  5.0  6.0

In [169]:
df.aggregate({
    'A': ['sum', 'min'],
    'B': ['max', 'min'],
    'C': [np.sum, np.mean],
})


A    B     C
max    NaN  8.0   NaN
mean   NaN  NaN   6.0
min    1.0  2.0   NaN
sum   12.0  NaN  18.0

In [170]:

df = pd.DataFrame(
    ([1, 2, 3], [4, 5, 6], [7, 8, 9]), 
    columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
0   1   2   3
1   4   5   6
2   7   8   9

In [171]:
df.aggregate(['mean'], axis='rows')


x1   x2   x3
mean  4.0  5.0  6.0

In [172]:
data = [
    [1, 4.7, 60],
    [3, 4.5, 45],
    [4, 4.8, 40],
    [1, 4.9, 58],
    [2, 4.1, 50],
    [2, 4.2, 49],
    [2, 4.4, 49],
    [3, 4.9, 46],
    [4, 4.3, 33],
]

stud_df = pd.DataFrame(data, columns=['Grade', 'Test_Mark', 'Time'])
stud_df

Grade  Test_Mark  Time
0      1        4.7    60
1      3        4.5    45
2      4        4.8    40
3      1        4.9    58
4      2        4.1    50
5      2        4.2    49
6      2        4.4    49
7      3        4.9    46
8      4        4.3    33

In [173]:
gr_stud_df = stud_df.groupby(by='Grade')


In [174]:
print(type(gr_stud_df))


pandas.core.groupby.generic.DataFrameGroupBy


In [175]:
gr_stud_df.groups


{1: [0, 3], 2: [4, 5, 6], 3: [1, 7], 4: [2, 8]}

In [176]:
gr_stud_df.agg('mean')


Test_Mark       Time
Grade                      
1       4.800000  59.000000
2       4.233333  49.333333
3       4.700000  45.500000
4       4.550000  36.500000

In [177]:
gr_stud_df.agg(['mean', 'min'])


Test_Mark            Time    
           mean  min       mean min
Grade                              
1      4.800000  4.7  59.000000  58
2      4.233333  4.1  49.333333  49
3      4.700000  4.5  45.500000  45
4      4.550000  4.3  36.500000  33

In [178]:
res = gr_stud_df.agg({
    'Test_Mark': ['mean', 'min'],
    'Time': ['min']
})

print(type(res))
res

<class 'pandas.core.frame.DataFrame'>


Test_Mark      Time
           mean  min  min
Grade                    
1      4.800000  4.7   58
2      4.233333  4.1   49
3      4.700000  4.5   45
4      4.550000  4.3   33

In [179]:
res['Test_Mark']['mean']


Grade
1    4.800000
2    4.233333
3    4.700000
4    4.550000
Name: mean, dtype: float64

In [180]:
df = pd.DataFrame({
    'x1': np.random.randint(10, 100, size=(200, )),
    'x2': np.random.choice(['low', 'high', 'medium'], size=(200, )),
    'x3': np.random.randint(-20, 30, size=(200, )),
})
df.head()

x1      x2  x3
0  27  medium -10
1  93     low  22
2  75  medium   4
3  49  medium -13
4  47  medium  13

In [185]:
group_df=df.groupby(by='x2')
res = group_df.agg({
    'x1': ['mean', 'max'],
    'x3': ['mean', 'max']
})

print(type(res))
res

<class 'pandas.core.frame.DataFrame'>


x1            x3    
             mean max      mean max
x2                                 
high    49.156250  99  4.921875  29
low     51.876923  98  3.138462  28
medium  52.704225  98  4.549296  29

In [186]:
import string

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

x1  x2  x3
A   7   2   8
B   3   6   7
C   1   1   0

In [187]:
df.to_csv('my_first_file.csv')


In [188]:

df = pd.read_csv('my_first_file.csv')
df.head(3)

Unnamed: 0  x1  x2  x3
0          A   7   2   8
1          B   3   6   7
2          C   1   1   0

In [189]:
df = pd.read_csv('my_first_file.csv', index_col=0)
df.head(3)

x1  x2  x3
A   7   2   8
B   3   6   7
C   1   1   0

In [190]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

x1  x2  x3
A   2   2   6
B   5   0   4
C   9   3   9

In [192]:
df.to_csv('my_second_fail.csv',index=False)

In [196]:
df = pd.read_csv('my_second_fail.csv')
df.head(3)

x1  x2  x3
0   2   2   6
1   5   0   4
2   9   3   9

In [201]:
#Задачки
#создайте фрейм и настройте правильные типы колонок
df = pd.DataFrame({'name': ['Misha','Mikhail','Mishanya','Mishka'],
                   'stage': np.array([2.] * 4, dtype='float32'),
                   'age': np.array([22] * 4, dtype='int32'),
                   'color': pd.Categorical(["blue", "blue", "blue", "синий"])
                   })
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   name    4 non-null      object  
 1   stage   4 non-null      float32 
 2   age     4 non-null      int32   
 3   color   4 non-null      category
dtypes: category(1), float32(1), int32(1), object(1)
memory usage: 292.0+ bytes


In [210]:
#Выберите числа в ряду ds1, которых нет в ряду ds2:
ds1 = pd.Series([1, 2, 3, 4, 5])
ds2 = pd.Series([4, 5, 6, 7, 8, 1, 9])
mask=ds1.isin(ds2)
print(ds1[~mask])

1    2
2    3
dtype: int64


In [218]:
#Оставьте в ряду два наиболее частых значения, остальные замените значением 'Другое':
ds = pd.Series([2, 2, 2, 4, 4, 4, 3, 1, 1, 1, 1, 4])
mask=ds.value_counts()
new_mask=max(mask)==mask
mask1=ds.replace(mask[~new_mask].index,'Другое')
print(mask1)

0     Другое
1     Другое
2     Другое
3          4
4          4
5          4
6     Другое
7          1
8          1
9          1
10         1
11         4
dtype: object


In [219]:
#Сделайте каждую первую букву в словах ряда заглавной:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])
def change(x):
  return x.title()
ds.apply(change)

0        How
1         To
2        Use
3    Pandas?
dtype: object

In [229]:
#Выберите записи с максимальным значением по колонке x1:
df = pd.DataFrame(
    np.random.randint(0, 4, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
mask=(df['x1']==df['x1'].max())
df=df[mask]
df

x1  x2  x3
1    3   2   0
8    3   2   0
10   3   3   3

In [241]:
#Выведите количество пропусков в каждой колонке данных:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df.isna().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [246]:
#Замените пропущенные значения в колонке Min.Price средним значениям по этой колонке:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
mean=df['Min.Price'].mean()
df['Min.Price'].fillna(mean,inplace=True)
df['Min.Price'].isna().sum()

0

In [256]:
#Отсортируйте и выведите фрейм с колонками в алфавитном порядке:
df = pd.DataFrame(np.random.randint(0, 10, size=(5, 6)), columns=list('fbecda'))
df.reindex(sorted(df.columns),axis=1)

a  b  c  d  e  f
0  6  6  8  1  6  1
1  0  2  6  0  7  1
2  8  5  1  2  9  8
3  9  5  3  8  1  1
4  8  3  1  8  1  1

In [269]:
#Отобразите каждую 20ю запись во фрейме и только колонки Manufacturer, Model, Type:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df1=df.loc[20::20,['Manufacturer', 'Model', 'Type']]
df1

Manufacturer    Model     Type
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [272]:
#Получите ряд, который содержит длины строк:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])
ds.str.len()

0    3
1    2
2    3
3    7
dtype: int64